### ISSUE TITLE
htmlwidgets - blank load

### ISSUE THREAD

**Issue by paulinshek** [att/rcloud.rcap#96]
The HTMLWIDGET widgets on other pages show as blank on pages not showing during the initial load. They refresh correctly on a control trigger.

**Comment by NattyE** [comment]
Is this linked to #98?

**Comment by NattyE** [comment]
This is due to the sizing of the iframe being set to 0. @gaborcsardi can you confirm?

**Comment by NattyE** [comment]
I believe this could be due to the widgets needing a default control setting.

**Comment by gaborcsardi** [comment]
The measurement of the widget's height is wrong (zero) if the widget is hidden. This is a bug in `rcloud.support`, and I'll fix it there. Hopefully there is a way of measuring the height of the widget without showing it.....

**Comment by gaborcsardi** [comment]
Unfortunately it is not possible to measure the height of a hidden element. So I can see two options now:

1. Fix this somehow from RCAP, to set the height of the widgets on RCAP dashboards differently, simply to `100%` or sg like this.
2. Show the widget temporarily, maybe off-screen, measure it, and then hide it again.

The second solution would fix similar potential issues in plain `mini.html` as well.

**Comment by shaneporter** [comment]
Pretty sure I remember this happening for standard offscreen plots. The height and width were being sent across as 0, so they weren't rendered either.

**Comment by gaborcsardi** [comment]
@shaneporter the size seems ok, actually, for html widgets at least.

The solution is to get rid of the initial and periodic resizer hooks. These are useful for the widgets in the notebook, but not for RCAP. In RCAP I'll just set all widgets to the prescribed sizes (which look good now), once and for all. The sizes of the RCAP controls never change, anyway, right?

**Comment by shaneporter** [comment]
Controls' containing 'boxes' height is fixed.

I *think* that their width, too, is fixed. 

However, nowhere is there a tablet of stone that states that their height or width is constant. Both can be expressed with variable widths according to CSS values.

For now, we can work with fixed size, but things can and probably will evolve.

**Comment by gaborcsardi** [comment]
@shaneporter That's fine, I'll just rely on size updates from the client size. :) So the size is not actually fixed, but it is updated whenever the JS tells us so.
